### PR TITLE
Flatten all filled fields to prevent editing

### PR DESCRIPTION
**Pull request by danielberkompas**
As seen in `pdf-forms` documentation here:

https://github.com/jkraemer/pdf-forms#query-form-fields-and-fill-out-pdf-forms-with-pdftk

I removed the add-hoc `flatten` and `secure` methods because they are no
longer needed. (And apparently they don't work.)

### CODE REVIEW

**Comment by jamonholmgren** [comment]
:+1: @danielberkompas you're a life saver. Thanks!

**Comment by danielberkompas** [comment]
Shouldn't this be merged by now? :smile:

**Comment by kevinvangelder** [comment]
Merging is overrated. :P They actually just contacted us again this week claiming it's still broken, so I'm waiting to hear back from Isaac.

**Comment by danielberkompas** [comment]
@clearsightstudio/owners anyone going to merge this?

**Comment by jamonholmgren** [comment]
@kevinvangelder would know.

**Comment by danielberkompas** [comment]
@kevinvangelder @jamonholmgren I'm gonna close this PR if no one merges this. :smile:

**Comment by jamonholmgren** [comment]
@kevinvangelder @kevinvangelder @kevinvangelder @kevinvangelder @kevinvangelder @kevinvangelder @kevinvangelder @kevinvangelder @kevinvangelder @kevinvangelder @kevinvangelder @kevinvangelder @kevinvangelder @kevinvangelder @kevinvangelder @kevinvangelder @kevinvangelder @kevinvangelder @kevinvangelder @kevinvangelder @kevinvangelder @kevinvangelder @kevinvangelder @kevinvangelder @kevinvangelder @kevinvangelder @kevinvangelder @kevinvangelder @kevinvangelder @kevinvangelder @kevinvangelder @kevinvangelder @kevinvangelder @kevinvangelder @kevinvangelder @kevinvangelder @kevinvangelder @kevinvangelder @kevinvangelder @kevinvangelder @kevinvangelder @kevinvangelder @kevinvangelder @kevinvangelder @kevinvangelder @kevinvangelder @kevinvangelder @kevinvangelder @kevinvangelder @kevinvangelder @kevinvangelder @kevinvangelder @kevinvangelder @kevinvangelder @kevinvangelder @kevinvangelder @kevinvangelder @kevinvangelder @kevinvangelder @kevinvangelder

**Pull request merged**
